### ISSUE TITLE
bundle.js -> "unexpected token >"

### ISSUE THREAD

**Issue by denzelvb** [sar-gupta/space#1]
When trying to run the application locally (to contribute) I get an error while running the electron app

`Uncaught SyntaxError: Unexpected token <`

Do you know about this issue?

EDIT: this is only when running 'yarn run electron'.

If I just run the web version it's fine.

**Comment by sar-gupta** [comment]
Hey @denzelvb,
Looks like some issue related to babel.
Can you paste the complete console output?

**Comment by sar-gupta** [comment]
Closing due to no-response

**Comment by a1diablo** [comment]
Hi @sar-gupta , I'm also facing the same issue when I do 'yarn run electron'. The console output shared above was complete and I'm able to run it fine on the web. Any suggestions?

**Comment by a1diablo** [comment]
![capture](https://user-images.githubusercontent.com/8023502/50588010-29ca6200-0ea6-11e9-8d44-c62c1425c3cd.PNG)

Also, it seems that index.html is routed as bundle.js and being tried to parse as html and hence the error. I don't have much experience with webpack and was just trying to run it out of the box. Do let me know if you need more input from me.

**Comment by sar-gupta** [comment]
@abhimanyu-bst 
Seems to work fine for me 
![image](https://user-images.githubusercontent.com/22498965/50588365-baee0880-0ea7-11e9-82e8-ff658101d979.png)

Is there any output on the terminal?

**Comment by sar-gupta** [comment]
@abhimanyu-bst 
I think it's because you've not built the react app yet. When you run it with webpack-dev-server, it's served from memory and the public/dist/ folder is not actually created on disk (please check the existence of this folder to confirm the source of error). 

So first, you would be required to build it by `yarn run build:prod`, which would create the /public/dist/ folder, and then run `yarn run electron` to run the app. Do let me know if it worked :)

**Comment by a1diablo** [comment]
Yes, exactly the problem. Please do update the readme for the same. Thanks for the response. Great work!
